In [1]:
import numpy as np
import pandas as pd
data = {
'produit': ['Riz (1kg)', 'Huile (1L)', 'Tomate (kg)', 'Poulet (kg)',
'Plantain (kg)', 'Pain (baguette)', 'Sucre (1kg)'],
'marche': ['Mokolo', 'Sandaga', 'Mokolo', 'Marché Central',
'Sandaga', 'Marché Central', 'Mokolo'],
'prix_fcfa': [500, 1200, 250, 2500, 300, 200, 600],
'stock_kg': [500, 200, 150, 80, 350, None, 420],
'bio': [False, False, True, False, True, False, None],
}
df = pd.DataFrame(data)
print(df)

           produit          marche  prix_fcfa  stock_kg    bio
0        Riz (1kg)          Mokolo        500     500.0  False
1       Huile (1L)         Sandaga       1200     200.0  False
2      Tomate (kg)          Mokolo        250     150.0   True
3      Poulet (kg)  Marché Central       2500      80.0  False
4    Plantain (kg)         Sandaga        300     350.0   True
5  Pain (baguette)  Marché Central        200       NaN  False
6      Sucre (1kg)          Mokolo        600     420.0   None

In [2]:
"Exercice 1"
"question 1 "
df.shape

(7, 5)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   produit    7 non-null      object
 1   marche     7 non-null      object
 2   prix_fcfa  7 non-null      int64
 3   stock_kg   6 non-null      float64
 4   bio        6 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 412.0+ bytes

In [4]:
df.isnull().sum()

produit      0
marche       0
prix_fcfa    0
stock_kg     1
bio          1
dtype: int64

In [5]:
df.describe()

         prix_fcfa    stock_kg
count     7.000000    6.000000
mean    792.857143  283.333333
std     825.847328  165.005050
min     200.000000   80.000000
25%     275.000000  162.500000
50%     500.000000  275.000000
75%     900.000000  402.500000
max    2500.000000  500.000000

In [6]:
print(f"la moyenne est : {df['prix_fcfa'].mean()} et le prix mediane est : {df['prix_fcfa'].median()}")

la moyenne est : 792.8571428571429 et le prix mediane est : 500.0

In [7]:
df['marche'].value_counts()

marche
Mokolo            3
Sandaga           2
Marché Central    2
Name: count, dtype: int64

In [8]:
""" question 1.2 -- """

' question 1.2 -- '

In [9]:
df.iloc[:, [0, 2]]

           produit  prix_fcfa
0        Riz (1kg)        500
1       Huile (1L)       1200
2      Tomate (kg)        250
3      Poulet (kg)       2500
4    Plantain (kg)        300
5  Pain (baguette)        200
6      Sucre (1kg)        600

In [10]:
df[df['prix_fcfa'] > 500 ]

       produit          marche  prix_fcfa  stock_kg    bio
1   Huile (1L)         Sandaga       1200     200.0  False
3  Poulet (kg)  Marché Central       2500      80.0  False
6  Sucre (1kg)          Mokolo        600     420.0   None

In [11]:
df[(df['bio'] == True ) & (df['marche'] == 'Mokolo')]

       produit  marche  prix_fcfa  stock_kg   bio
2  Tomate (kg)  Mokolo        250     150.0  True

In [12]:
df.query('stock_kg > 300 and prix_fcfa < 600')

         produit   marche  prix_fcfa  stock_kg    bio
0      Riz (1kg)   Mokolo        500     500.0  False
4  Plantain (kg)  Sandaga        300     350.0   True

In [13]:
""" Exercice 2 """

' Exercice 2 '

In [14]:
ventes_sales = pd.DataFrame({
'date': ['2024-01-15', '2024-01-15', '2024-01-16', '2024-01-16',
'2024-01-17', '2024-01-15', None, '2024-01-18'],
'vendeur': ['Alice', 'BOB', 'alice', 'Bob', 'ALICE', 'Bob',
'Charlie', 'Charlie'],
'produit': ['Riz', 'Huile', 'Riz', 'Tomate', 'Riz', 'Huile',
'Sucre', 'Sucre'],
'quantite': [10, 5, 8, 20, -3, 5, 15, 1500], 
'prix_unit': [500, 1200, 500, 250, 500, 1200, None, 600],
'total': [5000, 6000, 4000, 5000, -1500, 6000, None, 900000],
})

In [15]:
print(ventes_sales)

         date  vendeur produit  quantite  prix_unit     total
0  2024-01-15    Alice     Riz        10      500.0    5000.0
1  2024-01-15      BOB   Huile         5     1200.0    6000.0
2  2024-01-16    alice     Riz         8      500.0    4000.0
3  2024-01-16      Bob  Tomate        20      250.0    5000.0
4  2024-01-17    ALICE     Riz        -3      500.0   -1500.0
5  2024-01-15      Bob   Huile         5     1200.0    6000.0
6        None  Charlie   Sucre        15        NaN       NaN
7  2024-01-18  Charlie   Sucre      1500      600.0  900000.0

In [16]:
"Question 2.1"
" valeurs manquante pour chaque colonne "
ventes_sales.isnull().sum()

date         1
vendeur      0
produit      0
quantite     0
prix_unit    1
total        1
dtype: int64

In [17]:
print(ventes_sales.duplicated().sum())

0

In [18]:
" dans le dataset on a les valeurs negatives en quantite, on a des donnees manquantes, on a des produits donc la quantite est vraiment eleve contrairement a d'autre, on a les vendeurs donc le nom ou prenom mal formule"

" dans le dataset on a les valeurs negatives en quantite, on a des donnees manquantes, on a des produits donc la quantite est vraiment eleve contrairement a d'autre, on a les vendeurs donc le nom ou prenom mal formule"

In [19]:
"Question 2.2"
correction = {'ALICE':'Alice', 'BOB':'Bob', 'alice':'Alice'}
ventes_sales['vendeur'] = ventes_sales['vendeur'].replace(correction)
print(ventes_sales['vendeur'])

0      Alice
1        Bob
2      Alice
3        Bob
4      Alice
5        Bob
6    Charlie
7    Charlie
Name: vendeur, dtype: object

In [20]:
ventes_sales.dropna(subset=['date'])

         date  vendeur produit  quantite  prix_unit     total
0  2024-01-15    Alice     Riz        10      500.0    5000.0
1  2024-01-15      Bob   Huile         5     1200.0    6000.0
2  2024-01-16    Alice     Riz         8      500.0    4000.0
3  2024-01-16      Bob  Tomate        20      250.0    5000.0
4  2024-01-17    Alice     Riz        -3      500.0   -1500.0
5  2024-01-15      Bob   Huile         5     1200.0    6000.0
7  2024-01-18  Charlie   Sucre      1500      600.0  900000.0

In [21]:
print(ventes_sales.duplicated().sum())

1

In [22]:
ventes_sales.drop_duplicates(inplace=True)

In [23]:
ventes_sales['prix_unit'] = ventes_sales['prix_unit'].fillna(ventes_sales.groupby('produit')['prix_unit'].transform('median'))

In [24]:
ventes_sales['quantite'] = ventes_sales['quantite'].clip(lower=0)
medians = ventes_sales.groupby('produit')['quantite'].median().astype(int)
ventes_sales.loc[ventes_sales['quantite'] > 200, 'quantite'] = ventes_sales.loc[ventes_sales['quantite'] > 200, 'produit'].map(medians)
print(ventes_sales['quantite'])

0     10
1      5
2      8
3     20
4      0
6     15
7    757
Name: quantite, dtype: int64

In [25]:
total = ventes_sales['quantite'] * ventes_sales['prix_unit']
print(total)

0      5000.0
1      6000.0
2      4000.0
3      5000.0
4         0.0
6      9000.0
7    454200.0
dtype: float64

In [26]:
"Exercice 3 "

'Exercice 3 '

In [27]:
ventes = pd.DataFrame({
'vendeur': ['Alice','Bob','Alice','Bob','Alice','Charlie','Charlie'],
'produit': ['Riz','Huile','Riz','Tomate','Riz','Sucre','Sucre'],
'quantite':[10, 5, 8, 20, 10, 15, 12],
'prix_unit':[500, 1200, 500, 250, 500, 600, 600],
'total': [5000, 6000, 4000, 5000, 5000, 9000, 7200],
})
print(ventes)

   vendeur produit  quantite  prix_unit  total
0    Alice     Riz        10        500   5000
1      Bob   Huile         5       1200   6000
2    Alice     Riz         8        500   4000
3      Bob  Tomate        20        250   5000
4    Alice     Riz        10        500   5000
5  Charlie   Sucre        15        600   9000
6  Charlie   Sucre        12        600   7200

In [28]:

analyse_vendeur = ventes.groupby('vendeur')[['quantite', 'total']].sum()
print("a) Analyse par vendeur :\n", analyse_vendeur)

a) Analyse par vendeur :
          quantite  total
vendeur
Alice          28  14000
Bob            25  11000
Charlie        27  16200

In [29]:
pivot = ventes.pivot_table(values='total', index='vendeur', columns='produit', aggfunc='sum', fill_value=0)
print(pivot)

produit  Huile    Riz  Sucre  Tomate
vendeur
Alice        0  14000      0       0
Bob       6000      0      0    5000
Charlie      0      0  16200       0

In [30]:
ventes['ca_vendeur'] = ventes.groupby('vendeur')['total'].transform('sum')
print("\nc) DataFrame avec CA vendeur :\n", ventes)

c) DataFrame avec CA vendeur :
    vendeur produit  quantite  prix_unit  total  ca_vendeur
0    Alice     Riz        10        500   5000       14000
1      Bob   Huile         5       1200   6000       11000
2    Alice     Riz         8        500   4000       14000
3      Bob  Tomate        20        250   5000       11000
4    Alice     Riz        10        500   5000       14000
5  Charlie   Sucre        15        600   9000       16200
6  Charlie   Sucre        12        600   7200       16200

In [33]:
print(ventes['ca_vendeur'])

0    14000
1    11000
2    14000
3    11000
4    14000
5    16200
6    16200
Name: ca_vendeur, dtype: int64

In [31]:
ventes['part_ca'] = (ventes['total'] / ventes['ca_vendeur']) * 100
print("\nd) DataFrame avec part du CA (%) :\n", ventes)

d) DataFrame avec part du CA (%) :
    vendeur produit  quantite  prix_unit  total  ca_vendeur    part_ca
0    Alice     Riz        10        500   5000       14000  35.714286
1      Bob   Huile         5       1200   6000       11000  54.545455
2    Alice     Riz         8        500   4000       14000  28.571429
3      Bob  Tomate        20        250   5000       11000  45.454545
4    Alice     Riz        10        500   5000       14000  35.714286
5  Charlie   Sucre        15        600   9000       16200  55.555556
6  Charlie   Sucre        12        600   7200       16200  44.444444

In [33]:
vendeurs_info = pd.DataFrame({
'vendeur': ['Alice', 'Bob', 'Charlie', 'Diana'],
'region': ['Littoral', 'Centre', 'Centre', 'Ouest'],
'anciennete_an': [3, 7, 1, 5],
})
objectifs = pd.DataFrame({
'vendeur': ['Alice', 'Bob', 'Charlie'],
'objectif_ca': [20000, 25000, 15000],
})

In [34]:
print(vendeurs_info)

   vendeur    region  anciennete_an
0    Alice  Littoral              3
1      Bob    Centre              7
2  Charlie    Centre              1
3    Diana     Ouest              5

In [35]:
# Fusion des ventes avec les infos vendeurs
df_fusion = pd.merge(ventes, vendeurs_info, on='vendeur', how='left')

In [36]:
# On utilise la table complète des vendeurs pour ne perdre personne
df_final = pd.merge(df_fusion, objectifs, on='vendeur', how='left')

In [37]:
# 1. Calcul du CA total par vendeur sur le DataFrame fusionné
ca_par_vendeur = df_final.groupby('vendeur')[['total', 'objectif_ca']].first().reset_index()

# 2. Calcul du taux
ca_par_vendeur['taux_realisation'] = (ca_par_vendeur['total'] / ca_par_vendeur['objectif_ca']) * 100

# 3. Gestion du cas Diana (remplacer NaN par 0 ou un message)
ca_par_vendeur['taux_realisation'] = ca_par_vendeur['taux_realisation'].fillna(0)
print(ca_par_vendeur[['vendeur', 'total', 'objectif_ca', 'taux_realisation']])

   vendeur  total  objectif_ca  taux_realisation
0    Alice   5000        20000              25.0
1      Bob   6000        25000              24.0
2  Charlie   9000        15000              60.0